/**
 * Shared UI utilities. Currently just `cn` — the standard shadcn/ui class merger
 * (clsx for conditional classes + tailwind-merge to resolve conflicting Tailwind
 * utilities, last-wins). Generated by shadcn; left as-is.
 */
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
